### ISSUE TITLE
Multiple samples in a reading cycle and intervals

### ISSUE THREAD

**Issue by marcob1281** [binh-bk/SDS011#1]
a quick question: how many samples are collected each reading cycle?
what is the optimal reading interval in your experience?
thanks

**Comment by bi2air** [comment]
Air is continuously drawn by the fan so the air sample is a stream rather than "batches".
On the interval reading, I selected a one-minute cycle for ambient air quality monitoring. The interval depends on how quickly the concentration is changing. The sensor can yield every second reading at the highest resolution, but that comes with the burden to process a lot of data afterward.

**Comment by marcob1281** [comment]
got it
thanks for the explanation

Marco Barbato


Il giorno mar 2 feb 2021 alle ore 10:09 Binh Ng. <notifications@github.com>
ha scritto:
